DCRM/urls.py
# coding=utf-8

"""
DCRM - Darwin Cydia Repository Manager
Copyright (C) 2017  WU Zheng <i.82@me.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from WEIPDCRM.api import get_router
from WEIPDCRM.views import publish
from WEIPDCRM.views.admin import release
from WEIPDCRM.views.admin import upload
from WEIPDCRM.views.admin.help import about
from WEIPDCRM.views.admin.help import statistics

theme_module = settings.THEME

urlpatterns = [
    # Notice: Good Bro! Use 'include' to import urls from other apps.
    url(r'^', include('WEIPDCRM.styles.' + theme_module + '.urls')),
    url(r'^comments/', include('fluent_comments.urls')),
    
    # Basic List
    url(
        r'^(?P<resource_name>(CydiaIcon(.png)?|Release(.gpg)?|Packages(.gz|.bz2)?))$',
        publish.basic_resource_fetch,
        name='basic_resource_fetch'
    ),
    url(
        r'^debs/(?P<package_id>\d+)\.deb$',
        publish.package_file_fetch,
        name='package_file_fetch'
    ),
    url(
        r'^debs/(?P<package_name>.+?)/(?P<package_id>(\d+|latest))\.deb$',
        publish.package_file_fetch,
        name='package_file_fetch_with_name'
    ),
    
    # Admin Panel
    url(r'^admin/', admin.site.urls),
    url(r'^admin/upload/$', upload.upload_view, name='upload'),
    url(r'^admin/upload/version/$', upload.upload_version_view, name='version_add'),
    url(r'^admin/upload/screenshots/(?P<package_id>\d+)/(?P<gallery_slug>[0-9A-Za-z|_\-]+)/?$', upload.upload_screenshots_view, name='screenshots_add'),
    url(r'^admin/release/set-default/(?P<release_id>\d+)/?$', release.set_default_view, name='set_default_release'),
    url(r'^admin/help/about/$', about.about_view, name='help_about'),
    url(r'^admin/help/statistics/$', statistics.statistics_view, name='help_statistics'),

    # Photologue
    url(r'^photologue/', include('photologue.urls', namespace='photologue'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.ENABLE_REDIS is True:
    urlpatterns.append(url(r'^admin/sites/django-rq/', include('django_rq.urls')))

if settings.ENABLE_API is True:
    urlpatterns += [
        url(r'^api/', include(get_router().urls)),
        url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
    ]


handler400 = 'WEIPDCRM.views.error.bad_request'
handler404 = 'WEIPDCRM.views.error.page_not_found'
handler500 = 'WEIPDCRM.views.error.server_error'

WEIPDCRM/styles/DefaultStyle/urls.py
# coding=utf-8

"""
DCRM - Darwin Cydia Repository Manager
Copyright (C) 2017  WU Zheng <i.82@me.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from django.conf.urls import url

from .views.index import IndexView
from .views.package import PackageView
from .views.section import SectionView
from .views.search import search_view
from .views.chart import ChartView
from .views.section_list import SectionListView

from django.views.decorators.cache import cache_page
from django.conf import settings


def cache():
    return cache_page(getattr(settings, 'CACHE_TIME', 0)) \
        if getattr(settings, 'ENABLE_CACHE', False) else lambda x: x

urlpatterns = [
    url(r'^$', cache()(IndexView.as_view()), name='index'),
    url(r'^index/(?P<page>\d*)/?$', cache()(IndexView.as_view()), name='index_page'),
    url(r'^package/(?P<package_id>\d+)/?$', cache()(PackageView.as_view()), name='package_id'),
    url(r'^package/(?P<package_id>\d+)/(?P<action_name>[0-9A-Za-z]+)/?$', cache()(PackageView.as_view()), name='package_action'),
    url(r'^search/?$', cache()(search_view), name='search'),
    url(r'^chart/?$', cache()(ChartView.as_view()), name='chart'),
    url(r'^section/list/?$', cache()(SectionListView.as_view()), name='section_list'),
    url(r'^section/list/(?P<page>\d*)/?$', cache()(SectionListView.as_view()), name='section_list_page'),
    url(r'^section/(?P<section_id>\d+)/?$', cache()(SectionView.as_view()), name='section_id'),
    url(r'^section/(?P<section_id>\d+)/(?P<page>\d*)/?$', cache()(SectionView.as_view()), name='section_id_page'),
]

WEIPDCRM/models/version.py
# coding=utf-8

"""
DCRM - Darwin Cydia Repository Manager
Copyright (C) 2017  WU Zheng <i.82@me.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from __future__ import unicode_literals

import os
import re
import uuid
import shutil
import hashlib

from debian.debian_support import NativeVersion
from debian.deb822 import PkgRelation
from django.dispatch import receiver
from django.urls import reverse
from django.db import models
from django.core import urlresolvers
from django.core.validators import URLValidator
from django.core.validators import validate_slug
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.conf import settings

from preferences import preferences
from photologue.models import Gallery

from WEIPDCRM.models.os_version import OSVersion
from WEIPDCRM.models.device_type import DeviceType
from WEIPDCRM.models.section import Section
from WEIPDCRM.models.debian_package import DebianPackage

from WEIPDCRM.tools import mkdir_p


if settings.ENABLE_REDIS is True:
    import django_rq


def write_to_package_job(control, path, callback_version_id):
    # copy to temporary
    """
    This job will be called when any field in .deb file control part
    has been edited.
    
    :param control: New Control Dict
    :type control: dict
    :param path: Original Package Path
    :type path: str
    :param callback_version_id: Callback Version ID, for callback query
    :type callback_version_id: int
    """
    abs_path = os.path.join(settings.MEDIA_ROOT, path)
    temp_path = os.path.join(settings.TEMP_ROOT, str(uuid.uuid1()) + '.deb')
    shutil.copyfile(abs_path, temp_path)
    # read new package
    temp_package = DebianPackage(temp_path)
    temp_package.control = control
    # save new package
    temp_package.save()
    t_version = Version.objects.get(id=callback_version_id)
    t_version.write_callback(temp_package.path)


def validate_reversed_domain(value):
    """
    Apple's identifier.
    """
    pattern = re.compile(r"^[0-9A-Za-z.+\-]{2,}$")
    if not pattern.match(value):
        raise ValidationError(
            _("We recommend using a reverse-domain name style string (i.e., com.domainname.appname).")
        )


def validate_version(value):
    """
    Debian standard version format.
    """
    try:
        NativeVersion(value)
    except ValueError as e:
        raise ValidationError(
            _("Invalid version number.")
        )


def validate_name(value):
    """
    Value-Detail based names.
    """
    pattern = re.compile(r"[^<>]")
    if not pattern.match(value):
        raise ValidationError(
            _("Name cannot contain < or >.")
        )


def validate_relations(value):
    """
    Package Lists
    """
    relations = PkgRelation.parse_relations(value)
    for relation in relations:
        for rel in relation:
            if len(rel) == 3:
                raise ValidationError(
                    _("Cannot parse package relationship \"%s\"") % rel.get("name", "untitled")
                )


bugs_validator = URLValidator(
    schemes=["bts-type", "debbugs"],
    message=_("Enter a valid url of the bug tracking system."),
    code="invalid"
)


def validate_bugs(value):
    """
    Inherits from a Built-in URLValidator
    """
    return bugs_validator(value)


class Version(models.Model):
    """
    DCRM Base Model: Version
    This model manages all versions generated from .deb files.
    
    All database fields corresponding to the original control
    part in deb files will be prefixed by 'c_' except foreign keys.
    """
    class Meta(object):
        verbose_name = _("Version")
        verbose_name_plural = _("Versions")
    
    @staticmethod
    def get_model_fields(self):
        """
        Access the fields of Version model via _meta table
        :return: An array of fields in Version class
        """
        return self._meta.fields
    
    # Base Property
    id = models.AutoField(
        primary_key=True,
        editable=False
    )
    enabled = models.BooleanField(
        verbose_name=_("Enabled"),
        default=False,
        db_index=True
    )  # OK
    created_at = models.DateTimeField(
        verbose_name=_("Created At"),
        auto_now_add=True
    )  # OK
    
    def __str__(self):
        return self.c_package + ' (' + self.c_version + ')'
    
    def get_external_storage_link(self):
        """
        This getter method for storage_link property generates outer
        link for actual downloads.
        
        :return: External Storage Link
         :rtype: str
        """
        ext_path = os.path.join(str(preferences.Setting.resources_alias), self.storage.name)
        return ext_path
    
    storage_link = property(get_external_storage_link)
    
    def get_frontend_storage_link(self):
        """
        This getter method for frontend_link property generates outer
        link for frontend jumps.
        
        :return: External Storage Link
         :rtype: str
        """
        if preferences.Setting.download_count:
            return reverse("package_file_fetch", kwargs={
                'package_id': self.id
            })
        else:
            return self.get_external_storage_link()
    
    frontend_link = property(get_frontend_storage_link)
    
    def get_admin_url(self):
        """
        :return: URL String
        :rtype: str
        """
        content_type = ContentType.objects.get_for_model(self.__class__)
        return urlresolvers.reverse(
            "admin:%s_%s_change" % (content_type.app_label, content_type.model),
            args=(self.id,)
        )
    
    @staticmethod
    def get_change_list_url():
        """
        :return: URL String
        :rtype: str
        """
        content_type = ContentType.objects.get_for_model(Version)
        return urlresolvers.reverse(
            "admin:%s_%s_changelist" % (content_type.app_label, content_type.model)
        )
    
    # Compatibility
    os_compatibility = models.ManyToManyField(
        OSVersion,
        verbose_name=_("OS Compatibility"),
        blank=True
    )  # OK
    device_compatibility = models.ManyToManyField(
        DeviceType,
        verbose_name=_("Device Compatibility"),
        blank=True
    )  # OK
    
    # Update Logs
    update_logs = models.TextField(
        verbose_name=_("Update Logs"),
        blank=True,
        default=""
    )  # OK
    
    # File System
    storage = models.FileField(
        verbose_name=_("Storage"),
        upload_to="debs",
        max_length=255
    )  # OK

    # Warning: this field will store icon/file relative to MEDIA_URL,
    #          defined in settings.py.
    online_icon = models.FileField(
        verbose_name=_("Online Icon"),
        upload_to="package-icons",
        help_text=_("Choose an Icon (*.png) to upload"),
        max_length=255,
        blank=True,
        null=True,
    )  # OK

    def get_display_icon(self):
        """
        Get display icon from online_icon field, if not set, then
        return its section icon field
        :return:
        """
        if self.online_icon.name:
            file_path = self.online_icon.name
            return str(preferences.Setting.resources_alias) + file_path
        elif self.c_section:
            # self.c_section.icon has been validated by icon_link getter.
            return self.c_section.icon_link
        return None

    display_icon = property(get_display_icon)
    
    c_icon = models.CharField(
        verbose_name=_("Icon"),
        help_text=_("If there is no \"Online Icon\", this field will be taken."),
        max_length=255,
        null=True,
        blank=True,
        default=None
    )
    c_md5 = models.CharField(
        verbose_name=_("MD5Sum"),
        max_length=32,
        default=""
    )  # OK
    c_sha1 = models.CharField(
        verbose_name=_("SHA1"),
        max_length=40,
        default=""
    )  # OK
    c_sha256 = models.CharField(
        verbose_name=_("SHA256"),
        max_length=64,
        default=""
    )  # OK
    c_sha512 = models.CharField(
        verbose_name=_("SHA512"),
        max_length=128,
        default=""
    )  # OK
    c_size = models.BigIntegerField(
        verbose_name=_("Size"),
        default=0,
        help_text=_("The exact size of the package, in bytes.")
    )  # OK
    download_times = models.IntegerField(
        verbose_name=_("Download Times"),
        default=0,
    )  # OK
    c_installed_size = models.BigIntegerField(
        verbose_name=_("Installed-Size"),
        blank=True,
        null=True,
        default=0,
        help_text=_("The approximate total size of the package's installed files, "
                    "in KiB units.")
    )  # OK
    
    def get_c_installed_size_in_bytes(self):
        return self.c_installed_size * 1024

    c_installed_size_in_bytes = property(get_c_installed_size_in_bytes)
    
    def get_advanced_control_dict(self):
        """
        Generate advanced control dictionary (contains download and verify information).
        
        :rtype: dict
        :return: Advanced Control Dict
        """
        control_dict = self.get_control_dict()
        advanced_dict = {
            "Filename": self.frontend_link,
            "Size": self.c_size,
            "MD5sum": self.c_md5,

WEIPDCRM/styles/DefaultStyle/views.py
# coding=utf-8

"""
DCRM - Darwin Cydia Repository Manager
Copyright (C) 2017  WU Zheng <i.82@me.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published
by the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Notice: You have used class-based views, that's awesome.
        If not necessary, you can try function-based views.
        You may add lines above as license.
"""

from django.views.generic import ListView, DetailView

from WEIPDCRM.models.section import Section
from WEIPDCRM.models.version import Version
from WEIPDCRM.models.package import Package


class Index(ListView):
    """
    Notice: Class name should use CamelCase name method.
            Changed model to Package because it should list all
            enabled package and the latest version control once only.
    """
    model = Package
    context_object_name = 'package_list'
    template_name = 'frontend/index.html'


class PackageView(DetailView):
    """
    Notice: There is no need to override the default get_queryset method,
            because they remained their default behaviour.
    """
    model = Version
    context_object_name = 'package_info'
    pk_url_kwarg = 'package_id'
    template_name = 'frontend/package.html'

class SectionView(ListView):
    model = Section
    context_object_name = 'package_list'
    pk_url_kwarg = 'section_id'
    template_name = 'frontend/section.html'

WEIPDCRM/styles/DefaultStyle/templates/package/contact.html
{% extends "package/package.html" %}
{% load i18n staticfiles %}
{% block title %}{% blocktrans with package_info.c_name as c_name %}Contact {{ c_name }}{% endblocktrans %}{% endblock %}
{% block content %}
    <div class="contact">
        <div class="card">
            <div class="card-wrapper">
                <ul>
                    {% if package_info.author_name and package_info.author_email %}
                        <li>
                        <div class="contact-card blue">
                            <a target="_blank" href="mailto:{{ package_info.author_email }}?subject=
                                    {{ "Cydia/APT(A): "|escape }}{{ package_info.c_name|escape }}{{ " ("|escape }}{{ package_info.c_version }}{{ ")"|escape }}"
                               target="_blank">
                                <div class="panel">
                                    <div class="pic">
                                        <img class="icon" src="{% static "img/email.png" %}">
                                    </div>
                                    <div class="name">
                                        <h2>{% trans "Author" %}: {{ package_info.author_name }}</h2>
                                        <p>
                                            {% trans 'Source manager can <strong>NOT</strong> solve the function problem of package: you <strong>MUST</strong> contact the author.' %}
                                        </p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endif %}
                    </li>
                    <li>
                        {% if package_info.maintainer_name and package_info.maintainer_email %}
                            <div class="contact-card pink">
                                <a target="_blank" href="mailto:{{ package_info.maintainer_email }}?subject=
                                        {{ "Cydia/APT(A): "|escape }}{{ package_info.c_name|escape }}{{ " ("|escape }}{{ package_info.c_version }}{{ ")"|escape }}"
                                   target="_blank">
                                    <div class="panel">
                                        <div class="pic">
                                            <img class="icon" src="{% static "img/email.png" %}">
                                        </div>
                                        <div class="name">
                                            <h2>{% trans "Maintainer" %}: {{ package_info.maintainer_name }}</h2>
                                            <p>
                                                {% trans 'If you have questions when install or uninstall this package, please contact the maintainer.' %}
                                            </p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endif %}
                    </li>
                    <li>
                        {% if package_info.sponsor_name and package_info.sponsor_site %}
                            <div class="contact-card orange">
                                <a target="_blank" href="{{ package_info.sponsor_site }}" target="_blank">
                                    <div class="panel">
                                        <div class="pic">
                                            <img class="icon" src="{% static "img/safari.png" %}">
                                        </div>
                                        <div class="name">
                                            <h2>{% trans "Sponsor" %}: {{ package_info.sponsor_name }}</h2>
                                            <p>
                                                {% trans 'If the package is a commercial package, you can contact the sponsor to obtain commercial support.' %}
                                            </p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endif %}
                    </li>
                    <div class="clear"></div>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}
{% block footerscript %}
    <script type="text/javascript">
        $(document).ready(function () {
            // In Cydia
            if (navigator.userAgent.search(/Cydia/) !== -1) {
                $('a').attr("target", "_blank");
                $('.main').addClass("bg-cydia");
                $('.footer').remove();
                $('.breadcrumbs').remove();
                var $widget = $('.widget-area');
                if ($widget.children().length) {
                    $widget.css("margin", "auto");
                    $widget.css("padding", "0");
                } else {
                    $widget.remove();
                }
            }
        });
    </script>
{% endblock %}

WEIPDCRM/styles/DefaultStyle/templates/package/history.html
{% extends "package/package.html" %}
{% load i18n staticfiles %}
{% block title %}{% blocktrans with package_info.c_name as c_name %}History {{ c_name }}{% endblocktrans %}{% endblock %}

{% block content %}
    <div class="article">
        {% for version in version_list %}
            <div class="update-log">
                <div class="version">
                    <p>{{ version.c_version }}</p>
                    <span>{{ version.created_at | date:"Y-m-d H:i:s" }}</span>
                </div>
                <div class="clear"></div>
                <p>{{ version.update_logs | linebreaksbr }}</p>
                <a target="_blank" href="{% url "package_id" version.id %}?history=1">
                    {% trans "View this version" %} <i class="fa fa-angle-right" aria-hidden="true"></i>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block footerscript %}
    <script type="text/javascript">
        $(document).ready(function () {
            // In Cydia
            if (navigator.userAgent.search(/Cydia/) !== -1) {
                $('a').attr("target", "_blank");
                $('.main').addClass("bg-cydia");
                $('.breadcrumbs').remove();
                $('.footer').remove();
                var $widget = $('.widget-area');
                if ($widget.children().length) {
                    $widget.css("margin", "auto");
                    $widget.css("padding", "0");
                } else {
                    $widget.remove();
                }
            }
        });
    </script>
{% endblock %}